;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				c-electric-lt-gt
				c-indent-line-or-region
				cua-paste
				))

(setq mc/cmds-to-run-once
      '(
				))
